# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# ---
# include:
#   - board: nice_nano_v2
#     shield: sofle_left nice_view_adapter nice_view
#   - board: nice_nano_v2 
#     shield: sofle_right nice_view_adapter nice_view
#   - board: nice_nano_v2
#     shield: settings_reset
---
include:
  # Левая половина (энкодер + тачпад Azoteq на центральной прошивке не нужен дисплей)
  - board: nice_nano_v2
    shield: azoteq_sofle_left display_view_pro_micro
  # Правая половина
  - board: nice_nano_v2
    shield: azoteq_sofle_right display_view_pro_micro
  # Utility для сброса настроек
  - board: nice_nano_v2
    shield: settings_reset

