# Copyright (c) 2023 The ZMK Contributors
# SPDX-License-Identifier: MIT

identifier: sofle_dongle
name: sofle_dongle
type: shield
description: Sofle split keyboard dongle configuration
url: https://github.com/stelmakhdigital/zmk_sofle_niceview
requires: [nice_nano_v2]
features:
  - keys
  - display
siblings: []